---
name: semantic-release-rust-binary
description: GitHub Action to semantically release your Rust binary
author: EricCrosson
branding:
  icon: package
  color: orange

# Use a composite action for access to github.action_path
# (which is only supported in composite actions)

inputs:
  toolchain:
    description: Rust toolchain specification
    required: true
  compiled-targets:
    description: |
      Stringified JSON array describing each precompiled release artifact.

      Example:
      ```json
      [
        { "binary_name": "foo", "target": "x86_64-unknown-linux-musl" },
        { "binary_name": "bar", "target": "x86_64-unknown-linux-musl" },
        { "binary_name": "foo", "target": "aarch64-apple-darwin" },
        { "binary_name": "bar", "target": "aarch64-apple-darwin" }
      ]
      ```
    required: true
  cargo-registry-token:
    description: API token for writing to your cargo registry
  disable-semantic-release-cargo:
    description: Disable semantic-release-cargo in your release flow. Only takes effect if the action semantic-release config is used.
    default: false
  disable-semantic-release-git:
    description: Disable @semantic-release/git in your release flow. Only takes effect if the action semantic-release config is used.
    default: false
  next-version:
    description: Next semantic-release version number
    required: true
  submodules:
    description: Whether to checkout submodules
    required: true
  github_token:
    description: GitHub token used for authentication. Will use a token from GitHub App if provided, otherwise falls back to the default token.
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Fetch all history and tags so semantic-release can calculate the next release version.
        # (Even though _we_ have alerady calculated the next version, semantic-release will do it again.)
        fetch-depth: 0
        submodules: ${{ inputs.submodules }}
        persist-credentials: false

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install semantic-release configuration utilities
      uses: EricCrosson/install-github-release-binary@v2
      with:
        targets: |
          EricCrosson/is-semantic-release-configured@v1

    # Terminology:
    #
    # - The "host" is the repository calling this action.
    # - The "action" is this action.
    #
    # When we use the action's semantic-release configuration,
    # install node_modules into an ephemeral .semantic-release-action_rust directory.
    # Add this directory and the semantic-release manifest to the global gitignore.
    #
    # This has the following benefits:
    #
    # - @semantic-release/changelog does not try to commit the npm package manifest
    # - cargo does not include git-ignored files in the package upload

    - id: is-semantic-release-configured
      run: |
        : test for semantic-release configuration
        if is-semantic-release-configured; then
          echo "::debug::Detected semantic-release configuration, using host repository's configuration"
          echo "host-configuration=true" >> "$GITHUB_OUTPUT"
          echo "semantic_release=./node_modules/.bin/semantic-release" >> "$GITHUB_ENV"
        else
          echo "::debug::Did not detect semantic-release configuration, using this action's built-in configuration"
          echo "host-configuration=false" >> "$GITHUB_OUTPUT"
          echo "semantic_release=$GITHUB_WORKSPACE/.semantic-release-action_rust/semantic-release-binary/node_modules/.bin/semantic-release" >> "$GITHUB_ENV"
          echo "artifact_dir=$GITHUB_WORKSPACE/.semantic-release-action_rust/dist/" >> "$GITHUB_ENV"
          echo "node_workdir=$GITHUB_WORKSPACE/.semantic-release-action_rust/semantic-release-binary/" >> "$GITHUB_ENV"
          mkdir -p "$GITHUB_WORKSPACE/.semantic-release-action_rust/semantic-release-binary/"
        fi
      shell: bash

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      run: |
        : configure Node.js path
        echo NODE_PATH="$node_workdir${NODE_PATH:+":$NODE_PATH"}" >> "$GITHUB_ENV"
      shell: bash

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      run: |
        : configure git to ignore semantic-release manifest
        mkdir -p "$HOME/.config/git"
        echo "/.releaserc.json" >> "$HOME/.config/git/ignore"
        echo "/.semantic-release-action_rust/" >> "$HOME/.config/git/ignore"
      shell: bash

    # This action uploads assets to GitHub releases with the following metadata:
    #
    #    ```json
    #    {
    #      "path": <path>,
    #      "label": <binary-name>-<target-triple>
    #    }
    #    ```
    #
    #    This permits specifying which binary to install with
    #    EricCrosson/install-github-release-binary.
    #
    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      id: enumerate-binary-release-assets
      env:
        compiled_targets: ${{ inputs.compiled-targets }}
      run: |
        : enumerate binary release assets

        release_assets="$(
          jq \
            --null-input \
            --argjson compiled_targets "$compiled_targets" \
            '
              $compiled_targets
              | map({
                path: ".semantic-release-action_rust/dist/\(.binary_name)-\(.target)/\(.binary_name)-\(.target)",
                label: "\(.binary_name)-\(.target)" 
              })
            '
        )"

        # Array<{ path: string, label: string }>
        {
          echo "release-assets<<EOF"
          echo "$release_assets"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
      shell: bash

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      env:
        release_assets: ${{ steps.enumerate-binary-release-assets.outputs.release-assets }}
      run: |
        : install semantic-release manifest
        cp "${{ github.action_path }}/package.json" "${{ env.node_workdir }}/package.json"
        cp "${{ github.action_path }}/package-lock.json" "${{ env.node_workdir }}/package-lock.json"

        jq \
          --argjson release_assets "$release_assets" \
          '
            .plugins |= map(
              if type == "array" and .[0] == "@semantic-release/github" then
                .[1].assets += $release_assets
              else
                .
              end
            )
          ' \
          ${{ github.action_path }}/.releaserc.json \
          > .releaserc.json
      shell: bash

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && inputs.disable-semantic-release-cargo == 'true'
      env:
        tmpdir: ${{ runner.temp }}
      run: |
        : disable semantic-release-cargo
        jq \
          '.plugins |= map(select(type == "string" and . == "@semantic-release-cargo/semantic-release-cargo" | not))' \
          .releaserc.json \
        > "${tmpdir}/.releaserc.json"

        mv "${tmpdir}/.releaserc.json" .releaserc.json
      shell: bash

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && inputs.disable-semantic-release-git == 'true'
      env:
        tmpdir: ${{ runner.temp }}
      run: |
        : disable @semantic-release/git
        jq \
          '.plugins |= map(select(type == "array" and .[0] == "@semantic-release/git" | not))' \
          .releaserc.json \
        > "${tmpdir}/.releaserc.json"

        mv "${tmpdir}/.releaserc.json" .releaserc.json
      shell: bash

    # When the semantic-release-cargo plugin is disabled, the cargo manifest never has its version bumped.
    # Run the semantic-release-cargo's prepare step the binary directly.
    - name: Install semantic-release-cargo
      if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && inputs.disable-semantic-release-cargo == 'true'
      uses: EricCrosson/install-github-release-binary@v2
      with:
        targets: semantic-release-cargo/semantic-release-cargo@v2

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && inputs.disable-semantic-release-cargo == 'true'
      run: |
        : bump binary version
        semantic-release-cargo --verbose --verbose --verbose prepare ${{ inputs.next-version }}
      shell: bash

    - name: Download release artifacts
      uses: actions/download-artifact@v4
      with:
        path: ${{ env.artifact_dir }}

    # TODO: gate this behind the debug flag
    - run: |
        : display downloaded release artifacts
        ls -R
      working-directory: ${{ env.artifact_dir }}
      shell: bash

    - run: |
        : combine checksums
        cat **/*-SHA256SUM.txt | tee SHA256SUMS.txt
      working-directory: ${{ env.artifact_dir }}
      shell: bash

    - name: Configure Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Cache host npm dependencies
      if: steps.is-semantic-release-configured.outputs.host-configuration == 'true'
      uses: actions/cache@v4
      id: cache-host-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node-host-${{ hashFiles('package.json', 'package-lock.json') }}

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'true' && steps.cache-host-node-modules.outputs.cache-hit != 'true'
      run: |
        : install host npm dependencies
        npm ci --loglevel error
      shell: bash

    - name: Cache action npm dependencies
      if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      uses: actions/cache@v4
      id: cache-action-node-modules
      with:
        path: .semantic-release-action_rust/semantic-release-binary/node_modules
        key: ${{ runner.os }}-node-action-${{ hashFiles('.semantic-release-action_rust/semantic-release-binary/package-lock.json') }}

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && steps.cache-action-node-modules.outputs.cache-hit != 'true'
      run: |
        : install action npm dependencies
        npm ci --ignore-scripts --loglevel error
      working-directory: ${{ env.node_workdir }}
      shell: bash

    - run: |
        : semantic-release
        ${semantic_release}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CARGO_REGISTRY_TOKEN: ${{ inputs.cargo-registry-token }}
      shell: bash

    - run: |
        : write checksums to GitHub Actions summary
        {
          echo "## Binary Checksums"
          echo ""
          echo "| Binary | SHA-256 Checksum |"
          echo "| ------------- | ------------- |"

          while IFS= read -r line; do
            # Extract checksum and filename
            checksum=$(echo "$line" | awk '{print $1}')
            filename=$(echo "$line" | awk '{print $2}')
            # Remove leading asterisk if present
            filename=$(echo "$filename" | sed 's/^\*//g')
            binary_name=$(basename "$filename")

            echo "| $binary_name | $checksum |"
          done < SHA256SUMS.txt

          echo ""
        } >> $GITHUB_STEP_SUMMARY
      working-directory: ${{ env.artifact_dir }}
      shell: bash
