---
name: semantic-release-rust-library
description: GitHub Action to semantically release your Rust library
author: EricCrosson
branding:
  icon: package
  color: orange

# Use a composite action for access to github.action_path
# (which is only supported in composite actions)

inputs:
  toolchain:
    description: Rust toolchain specification
    required: false
    default: stable
  test-command:
    description: Command used to test your Rust program
    required: false
    default: cargo test
  disable-semantic-release-git:
    description: Disable @semantic-release/git in your release flow. Only takes effect if the action semantic-release config is used.
    default: false
  cargo-registry-token:
    description: API token for writing to your cargo registry
  submodules:
    description: Whether to checkout submodules
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Fetch all history and tags for calculating next semantic version
        fetch-depth: 0
        submodules: ${{ inputs.submodules }}

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      id: rust-toolchain
      with:
        toolchain: ${{ inputs.toolchain }}

    - uses: Swatinem/rust-cache@v2

    # Separate compilation from testing to accurately report the runtime of each
    - if: startsWith(inputs.test-command, 'cargo test')
      run: cargo test ${{ contains(inputs.test-command, '--locked') && '--locked' || '' }} --no-run
      shell: bash

    - run: ${{ inputs.test-command }}
      shell: bash

    - name: Install is-semantic-release-configured
      uses: EricCrosson/install-github-release-binary@v2
      with:
        targets: EricCrosson/is-semantic-release-configured@v1

    # Terminology:
    #
    # - The "host" is the repository calling this action.
    # - The "action" is this action.
    #
    # When we use the action's semantic-release configuration,
    # install node_modules into an ephemeral .semantic-release-action_rust directory.
    # Add this directory and the semantic-release manifest to the global gitignore.
    #
    # This has the following benefits:
    #
    # - @semantic-release/changelog does not try to commit the npm package manifest
    # - cargo does not include git-ignored files in the package upload

    - id: is-semantic-release-configured
      run: |
        : test for semantic-release configuration
        if is-semantic-release-configured; then
          echo "::debug::Detected semantic-release configuration, using host repository's configuration"
          echo "host-configuration=true" >> "$GITHUB_OUTPUT"
          echo "semantic_release=./node_modules/.bin/semantic-release" >> "$GITHUB_ENV"
        else
          echo "::debug::Did not detect semantic-release configuration, using this action's built-in configuration"
          echo "host-configuration=false" >> "$GITHUB_OUTPUT"
          echo "semantic_release=$GITHUB_WORKSPACE/.semantic-release-action_rust/semantic-release-library/node_modules/.bin/semantic-release" >> "$GITHUB_ENV"
          echo "node_workdir=$GITHUB_WORKSPACE/.semantic-release-action_rust/semantic-release-library/" >> "$GITHUB_ENV"
          mkdir -p "$GITHUB_WORKSPACE/.semantic-release-action_rust/semantic-release-library/"
        fi
      shell: bash

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      run: |
        : configure Node.js path
        echo NODE_PATH="$node_workdir${NODE_PATH:+":$NODE_PATH"}" >> "$GITHUB_ENV"
      shell: bash

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      run: |
        : configure git to ignore semantic-release manifest
        mkdir -p "$HOME/.config/git"
        echo "/.releaserc.json" >> "$HOME/.config/git/ignore"
        echo "/.semantic-release-action_rust/" >> "$HOME/.config/git/ignore"
      shell: bash

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      run: |
        : install semantic-release manifest
        cp "${{ github.action_path }}/package.json" "${{ env.node_workdir }}/package.json"
        cp "${{ github.action_path }}/package-lock.json" "${{ env.node_workdir }}/package-lock.json"
        cp "${{ github.action_path }}/.releaserc.json" ".releaserc.json"
      shell: bash

    - name: Install is-semantic-release-configured
      if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && inputs.disable-semantic-release-git == 'true'
      uses: EricCrosson/install-github-release-binary@v2
      with:
        targets: EricCrosson/configure-semantic-release-manifest@v1

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && inputs.disable-semantic-release-git == 'true'
      run: |
        : disable @semantic-release/git
        configure-semantic-release-manifest --in-place --remove @semantic-release/git
      shell: bash

    - name: Configure Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Cache host npm dependencies
      if: steps.is-semantic-release-configured.outputs.host-configuration == 'true'
      uses: actions/cache@v3
      id: cache-host-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node-host-${{ hashFiles('package.json', 'package-lock.json') }}

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'true' && steps.cache-host-node-modules.outputs.cache-hit != 'true'
      run: |
        : install host npm dependencies
        npm ci --loglevel error
      shell: bash

    - name: Cache action npm dependencies
      if: steps.is-semantic-release-configured.outputs.host-configuration == 'false'
      uses: actions/cache@v3
      id: cache-action-node-modules
      with:
        path: .semantic-release-action_rust/semantic-release-library/node_modules
        key: ${{ runner.os }}-node-action-${{ hashFiles('.semantic-release-action_rust/semantic-release-library/package-lock.json') }}

    - if: steps.is-semantic-release-configured.outputs.host-configuration == 'false' && steps.cache-action-node-modules.outputs.cache-hit != 'true'
      run: |
        : install action npm dependencies
        npm ci --ignore-scripts --loglevel error
      working-directory: ${{ env.node_workdir }}
      shell: bash

    - run: |
        : semantic-release
        ${semantic_release}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        CARGO_REGISTRY_TOKEN: ${{ inputs.cargo-registry-token }}
      shell: bash
